Repository COS301-SE-2024/ClassConnect, pull requests merged in 2024-07, with the labels that each got.

#123 Feature/upload functions
  .gitignore
  src/client/.gitignore
  src/client/bun.lockb
  src/client/package.json
  src/client/src/app.css
  src/client/src/lib/components/admin/Dashboard.svelte
  src/client/src/lib/components/admin/modals/add/+AddAdmin.svelte
  src/client/src/lib/components/admin/modals/add/+AddLecToWork.svelte
  src/client/src/lib/components/admin/modals/add/+AddLecturer.svelte
  src/client/src/lib/components/admin/modals/add/+AddStuToWork.svelte
  src/client/src/lib/components/admin/modals/add/+AddStudent.svelte
  src/client/src/lib/components/admin/modals/add/+AddToWorkSpace.svelte
  src/client/src/lib/components/admin/modals/add/+AddWorkspace.svelte
  src/client/src/lib/components/admin/modals/edit/+EditAdmin.svelte
  src/client/src/lib/components/admin/modals/edit/+EditLecturer.svelte
  src/client/src/lib/components/admin/modals/edit/+EditStudent.svelte
  src/client/src/lib/components/admin/modals/edit/+EditWorkspace.svelte
  src/client/src/lib/components/admin/modals/user/Add.svelte
  src/client/src/lib/components/common/Construction.svelte
  src/client/src/lib/components/student/Dashboard.svelte
  src/client/src/lib/server/s3Bucket.ts
  src/client/src/lib/store/index.ts
  src/client/src/lib/store/lessons.ts
  src/client/src/routes/(app)/admins/+page.server.ts
  src/client/src/routes/(app)/admins/page.server.test.ts
  src/client/src/routes/(app)/announcements/+page.server.ts
  src/client/src/routes/(app)/announcements/page.server.test.ts
  src/client/src/routes/(app)/dashboard/+page.svelte
  src/client/src/routes/(app)/lecturers/+page.server.ts
  src/client/src/routes/(app)/lecturers/page.server.test.ts
  src/client/src/routes/(app)/organisation/+page.server.ts
  src/client/src/routes/(app)/organisation/page.server.test.ts
  src/client/src/routes/(app)/students/+page.server.ts
  src/client/src/routes/(app)/students/page.server.test.ts
  src/client/src/routes/(app)/workspaces/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/[lesson]/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/page.server.test.ts
  src/client/src/routes/(app)/workspaces/page.server.test.ts
  src/client/src/routes/(auth)/signout/page.server.test.ts
  src/client/src/routes/(auth)/signup/+page.server.ts
  src/client/src/types.ts
  src/client/vite.config.ts
  src/client/vitest-setup.ts
Labels: backend

#137 Update/lecturer UI
  .gitignore
  src/client/package.json
  src/client/src/app.css
  src/client/src/lib/components/announcements/Card.svelte
  src/client/src/lib/components/common/Banner.svelte
  src/client/src/lib/components/common/Profile.svelte
  src/client/src/lib/components/common/Sandbox.svelte
  src/client/src/lib/components/common/Settings.svelte
  src/client/src/lib/components/common/SideBar.svelte
  src/client/src/lib/components/forms/UpdateGeneralDetails.svelte
  src/client/src/lib/components/forms/UpdatePassword.svelte
  src/client/src/lib/components/materials/Card.svelte
  src/client/src/lib/components/materials/MaterialsTab.svelte
  src/client/src/lib/components/modals/Delete.svelte
  src/client/src/lib/components/modals/announcement/Add.svelte
  src/client/src/lib/components/modals/announcement/Edit.svelte
  src/client/src/lib/components/modals/materials/DeleteMaterial.svelte
  src/client/src/lib/components/modals/materials/Preview.svelte
  src/client/src/lib/components/modals/materials/PreviewMaterial.svelte
  src/client/src/lib/components/modals/materials/UploadMaterial.svelte
  src/client/src/lib/components/modals/sandbox/AddToScene.svelte
  src/client/src/lib/components/modals/sandbox/LocalFile.svelte
  src/client/src/lib/components/modals/sandbox/Preview.svelte
  src/client/src/lib/components/modals/sandbox/UploadedFile.svelte
  src/client/src/lib/components/modals/settings/DeleteProfilePic.svelte
  src/client/src/lib/components/modals/settings/Preview.svelte
  src/client/src/lib/components/modals/settings/UploadPicture.svelte
  src/client/src/lib/components/sandbox/models/+ObjectSettings.svelte
  src/client/src/lib/components/workspaces/workspace/Sidebar.svelte
  src/client/src/lib/server/UploadHandler.ts
  src/client/src/lib/server/database/schemas/Material.ts
  src/client/src/lib/server/storage.ts
  src/client/src/lib/store/objects.ts
  src/client/src/routes/(app)/announcements/+page.svelte
  src/client/src/routes/(app)/settings/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/announcements/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/materials/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/materials/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/materials/material/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/sandbox/+page.svelte
  src/client/src/types.ts
Labels: frontend, environment

#140 Feature/lecturer grades
  bun.lockb
  package.json
  src/client/cypress/e2e/chart.cy.ts
  src/client/src/lib/components/common/AsessmentTable.svelte
  src/client/src/lib/components/common/GradeChart.svelte
  src/client/src/lib/components/common/GradeTable.svelte
  src/client/src/lib/components/common/LineChart.svelte
  src/client/src/lib/components/common/NoGrades.svelte
  src/client/src/lib/components/lecturer/grades/Table.svelte
  src/client/src/lib/components/workspaces/workspace/Sidebar.svelte
  src/client/src/routes/(app)/grades/+page.server.ts
  src/client/src/routes/(app)/grades/+page.svelte
  src/client/src/routes/(app)/profile/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/grades/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/grades/+page.svelte
Labels: frontend

#145 Feature/grades
  src/client/bun.lockb
  src/client/package.json
  src/client/src/lib/components/common/AsessmentTable.svelte
  src/client/src/lib/components/common/GradingTabs.svelte
  src/client/src/lib/components/common/StudentGrades.svelte
  src/client/src/lib/components/common/advancedTable.json
  src/client/src/lib/components/workspaces/workspace/Sidebar.svelte
  src/client/src/routes/(app)/grades/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/grades/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/studentmarks/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/studentmarks/+page.svelte
  src/client/tailwind.config.ts
Labels: frontend

#147 Update/admins
  resources/images/admin/workspace-creation.jpg
  src/client/bun.lockb
  src/client/package.json
  src/client/src/lib/components/common/Pagination.svelte
  src/client/src/lib/components/common/ZeroUsersCard.svelte
  src/client/src/lib/components/modals/Delete.svelte
  src/client/src/lib/components/modals/user/Add.svelte
  src/client/src/lib/components/modals/user/Edit.svelte
  src/client/src/lib/components/modals/workspace/Add.svelte
  src/client/src/lib/components/modals/workspace/Edit.svelte
  src/client/src/lib/components/workspaces/Admin.svelte
  src/client/src/lib/server/storage.ts
  src/client/src/routes/(app)/admins/+page.server.ts
  src/client/src/routes/(app)/admins/+page.svelte
  src/client/src/routes/(app)/admins/page.server.test.ts
  src/client/src/routes/(app)/lecturers/+page.svelte
  src/client/src/routes/(app)/organisation/+page.server.ts
  src/client/src/routes/(app)/students/+page.svelte
  src/client/src/routes/(app)/workspaces/+page.server.ts
  src/client/src/routes/(app)/workspaces/page.server.test.ts
Labels: frontend
