Repository COS301-SE-2024/ClassConnect, pull requests merged in 2024-08, with the labels that each got.

#155 Update/cypress testing
  bun.lockb
  cypress.config.ts
  cypress/e2e/adminAddLecturersAndStudents.cy.ts
  cypress/e2e/adminCreateOrganisation.ts
  cypress/e2e/adminCreateWorkspaceEnrolStudent.cy.ts
  cypress/e2e/auth.cy.ts
  cypress/e2e/lectureCreatesAndSchedulesLesson.cy.ts
  cypress/e2e/lecturerAdds3DModel.spec.ts
  cypress/e2e/lecturerManipulateAndAnnotate3D.cy.ts
  cypress/e2e/studentViewsAndAttendsLesson.cy.ts
  cypress/fixtures/example.json
  cypress/integration/materialManagement.spec.ts
  cypress/integration/organisationManagement.spec.ts
  cypress/integration/userManagement.spec.ts
  cypress/integration/workspaceManagement.spec.ts
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  tsconfig.json
Labels: testing

#169 Update/testing
  bun.lockb
  package.json
  src/client/bun.lockb
  src/client/package.json
  src/client/src/lib/components/common/OverviewShedule.svelte
  src/client/src/lib/components/common/Recordings.svelte
  src/client/src/lib/components/dashboards/Admin.svelte
  src/client/src/lib/components/dashboards/Student.svelte
  src/client/src/lib/components/lessons/lesson/Controls.svelte
  src/client/src/lib/components/workspaces/AdminWorkspaces.test.ts
  src/client/src/lib/server/database/schemas/Recording.ts
  src/client/src/lib/store/index.ts
  src/client/src/routes/(app)/admins/AdminAdmins.test.ts
  src/client/src/routes/(app)/workspaces/[workspace]/dashboard/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/[lesson]/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/[lesson]/page.server.test.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/video/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/materials/+page.server.ts
  src/client/src/types.ts
  src/client/tsconfig.json
  src/client/vite.config.ts
  src/client/vitest/AdminDashboard.test.ts
  src/client/vitest/LecturerDashboard.test.ts
  src/client/vitest/StudentDashboard.test.ts
Labels: workspace, testing

#184 Update/bugs without tests
  src/client/src/lib/components/common/FAQ.svelte
  src/client/src/lib/components/common/SideBar.svelte
  src/client/src/lib/components/workspaces/workspace/Sidebar.svelte
  src/client/src/routes/(app)/faq/+page.server.ts
  src/client/src/routes/(auth)/signin/+page.svelte
  src/client/src/routes/(auth)/signin/page.test.ts
  src/client/src/routes/(auth)/signup/+page.svelte
  src/client/src/routes/(auth)/signup/page.test.ts
  src/client/src/routes/+page.svelte
Labels: frontend

#185 Hotfix/admin
  src/client/src/lib/components/common/PageUnavailable.svelte
  src/client/src/lib/components/common/SubmitLoader.svelte
  src/client/src/lib/components/common/ZeroUsersCard.svelte
  src/client/src/lib/components/modals/Delete.svelte
  src/client/src/lib/components/modals/organisation/Add.svelte
  src/client/src/lib/components/modals/organisation/Edit.svelte
  src/client/src/lib/components/modals/user/Add.svelte
  src/client/src/lib/components/modals/user/Edit.svelte
  src/client/src/lib/components/modals/workspace/Add.svelte
  src/client/src/lib/components/modals/workspace/Edit.svelte
  src/client/src/lib/server/utils/users.ts
  src/client/src/routes/(app)/admins/+page.server.ts
  src/client/src/routes/(app)/admins/+page.svelte
  src/client/src/routes/(app)/announcements/+page.server.ts
  src/client/src/routes/(app)/lecturers/+page.server.ts
  src/client/src/routes/(app)/lecturers/+page.svelte
  src/client/src/routes/(app)/organisation/+page.svelte
  src/client/src/routes/(app)/students/+page.server.ts
  src/client/src/routes/(app)/students/+page.svelte
  src/client/src/routes/(app)/workspaces/+page.server.ts
  src/client/src/routes/(app)/workspaces/+page.svelte
  src/client/src/routes/(app)/workspaces/page.server.test.ts
Labels: frontend

#187 Recording Feature
  src/client/bun.lockb
  src/client/package.json
  src/client/src/lib/components/lessons/lesson/Controls.svelte
  src/client/src/lib/server/storage.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/[lesson]/+page.server.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/[lesson]/page.server.test.ts
  src/client/src/routes/(app)/workspaces/[workspace]/lessons/video/+page.svelte
Labels: workspace

#189 Update/assessments
  src/client/src/lib/components/workspaces/workspace/Sidebar.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/dashboard/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/environments/+page.svelte
  src/client/src/routes/(app)/workspaces/[workspace]/quizzes/[quiz]/+page.svelte
Labels: frontend

#216 Update/profile
  src/bun.lockb
  src/package.json
  src/src/lib/components/common/Banner.svelte
  src/src/lib/components/common/Profile.svelte
  src/src/lib/components/common/ProfileSettings.svelte
  src/src/lib/components/modals/announcement/Add.svelte
  src/src/lib/components/modals/announcement/Edit.svelte
  src/src/lib/components/modals/settings/DeleteProfilePic.svelte
  src/src/lib/components/modals/settings/Preview.svelte
  src/src/routes/(app)/profile/+page.server.ts
  src/src/routes/(app)/profile/page.server.test.ts
  src/src/routes/+layout.svelte
Labels: frontend
